global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask_app'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['5000:5000']
